<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<!-- Usa la misma variable que el resto de proyectos (net7.0) -->
		<TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>true</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<!-- Usa la misma versión que el resto de la solución -->
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="$(AspNetCoreVersion)" />
	</ItemGroup>

</Project>

